### ISSUE TITLE
qemu powernv broken with 4.20

### ISSUE THREAD

**Issue by shenki** [linuxppc/issues#227]
Booting Qemu powernv is broken with 4.20, getting stuck somewhere in the idle code:

```
qemu-system-ppc64 -M powernv -device ipmi-bmc-sim,id=bmc0 -device isa-ipmi-bt,bmc=bmc0,irq=10 -nographic -kernel arch/powerpc/boot/zImage.epapr
```
```
0xc0000000000264e0 in pnv_enter_arch207_idle_mode ()
(gdb) bt
#0  0xc0000000000264e0 in pnv_enter_arch207_idle_mode ()
#1  0xc000000000053000 in power7_idle_type ()
```

`-cpu Power9` is similar:
```
0xc0000000000264e0 in pnv_enter_arch207_idle_mode ()
(gdb) bt
#0  0xc0000000000264e0 in pnv_enter_arch207_idle_mode ()
#1  0xc000000000053000 in power7_idle_type ()
```

I am running Cedric's powernv-4.0 qemu branch https://github.com/legoater/qemu/commits/powernv-4.0

4.19.13 works okay.

**Comment by shenki** [comment]
I looked at slack for when this happened and I didn't see a resolution. I think Alistair and I were attempting to get some CI running and hit it.

It's long enough in the past that I don't see any value in chasing it up now.
