### ISSUE TITLE
ppc64_defconfig fails to boot in qemu

### ISSUE THREAD

**Issue by shenki** [linuxppc/issues#402]
v5.18-rc0 ppc64_defconfig fails to boot in qemu.

built with REHL9:

* powerpc64le-linux-gnu-gcc (GCC) 11.2.1 20210728 (Red Hat Cross 11.2.1-1)
* GNU ld version 2.35.2-1.fc34

```
qemu-system-ppc64 -nographic -nodefaults -M pseries,x-vof=off -kernel arch/powerpc/boot/zImage.pseries -serial mon:stdio 
```
```
( 700 ) Program Exception [ 1daf04c4 ]


    R0 .. R7           R8 .. R15         R16 .. R23         R24 .. R31
8000000000002000   000000001db73400   0000000000000000   0000000000000000   
000000001db7c400   8000000000000000   0000000000000000   0000000000000000   
0000000000000000   000000001db6e400   0000000000000000   0000000000000000   
0000000000000000   000000001daf449c   0000000000000000   0000000000000000   
0000000000000000   0000000040000008   0000000000000000   0000000000000000   
000000001daf04c4   0000000000000000   0000000000000000   0000000000000000   
0000000000000000   0000000000000000   0000000000000000   0000000000000000   
0000000000000000   0000000000000000   0000000000000000   0000000000000000   

    CR / XER           LR / CTR          SRR0 / SRR1        DAR / DSISR
        80000000   000000001daf04f0   0000000000400000   0000000000000000   
0000000020040000   0000000000400000   8000000000082000           00000000   

```

```
emu-system-ppc64 -nographic -nodefaults -M powernv9 -kernel arch/powerpc/boot/zImage.epapr -serial mon:stdio
```
```
   10.409830632,5] INIT: Starting kernel at 0x20010000, fdt at 0x306a6120 27842 bytes
[   10.481490807,3] ***********************************************
[   11.009953442,3] Fatal Exception 0xe40 at 000000003018af00  __toc_start+0x0  MSR 1000000000000000
[   11.010243386,3] CFAR : 000000002001c890 MSR  : 1000000000000000
[   11.010427333,3] SRR0 : 0000000030020214 SRR1 : 9000000000191002
[   11.010602706,3] HSRR0: 000000003018af00 HSRR1: 1000000000000000
[   11.010775543,3] DSISR: 00000000         DAR  : 0000000000000000
[   11.010947568,3] LR   : 0000000000000016 CTR  : 000000002001baa0
[   11.011150324,3] CR   : 42002804         XER  : 20040000
[   11.011311045,3] GPR00: 0000000000000019 GPR16: 0000000031c10000
[   11.011504043,3] GPR01: 00000000209f5bdc GPR17: 00000000300031bc
[   11.011681148,3] GPR02: 00000000300215d4 GPR18: 0000000000000000
[   11.011842899,3] GPR03: 0000000000000000 GPR19: 0000000000000000
[   11.012017027,3] GPR04: 0000000000000000 GPR20: 0000000000000000
[   11.012190884,3] GPR05: 00000000209f5ef4 GPR21: 0000000000000000
[   11.012355844,3] GPR06: 00000000209f60e1 GPR22: 000000003013f863
[   11.012536238,3] GPR07: 00000000209f5e74 GPR23: 0000000030120ece
[   11.012715833,3] GPR08: 0000000000000008 GPR24: 00000000301205f5
[   11.012879361,3] GPR09: 000000002001baa0 GPR25: 00000000209f6064
[   11.013054633,3] GPR10: 0000000000000008 GPR26: 00000000209f6028
[   11.013228830,3] GPR11: 0000001600000000 GPR27: 00000000209f65c8
[   11.013405767,3] GPR12: 000000003018af00 GPR28: 00000000209f5ef4
[   11.013582507,3] GPR13: 000000003018af00 GPR29: 00000000209f6084
[   11.013757789,3] GPR14: 0000000000000000 GPR30: 0000000020026e60
[   11.013919463,3] GPR15: 0000000000000000 GPR31: 00000000209f60ac
CPU 0000 Backtrace:
 S: 00000000209f5eec R: 000000002001bafc ! 
```

| kernel | pseries | powernv |
| v5.18-rc0 (ae085d7f9365) | x | x |
| v5.17 | x | x |
| v5.14 | x | ✓|
| v4.19 | x | ✓|
| v4.14 | x | ✓|

Just in case, I checked with the powerpc64-linux-gnu-gcc to make sure it wasn't the le variant of the cross compiler causing an issue.

**Comment by chleroy** [comment]
I guess these days nobody is booting zImage in QEMU, we are using vmlinux

See https://github.com/linuxppc/wiki/wiki/Booting-with-Qemu

**Comment by shenki** [comment]
> I guess these days nobody is booting zImage in QEMU, we are using vmlinux

I was trying to test a change to the wrapper. If it does not work then perhaps we should disable it for big endian?

**Comment by mpe** [comment]
The zImage built for `ppc64_defconfig` is a 32-bit binary. It seems that SLOF/qemu isn't loading it properly.

If I drop into SLOF and dump the *ppc64le* image, I see:
```
SLOF **********************************************************************
QEMU Starting
...
Ready!
0 > 400000 10 ldump
00400000: 70050048 00000060 00000060 00000060 ok
```

Which matches the zImage text:
```
Disassembly of section .text:

0000000000000000 <_start>:
       0:       70 05 00 48     b       570 <_zimage_start_lib>
       4:       00 00 00 60     nop
       8:       00 00 00 60     nop
       c:       00 00 00 60     nop
```

In contrast when booting the big endian zImage, I see:

```
SLOF **********************************************************************
QEMU Starting
...
Ready!
Ready!
0 > 400000 10 ldump
00400000: 00000000 00000000 00000000 00000000 ok
```

So when we jump to that it's all zeroes and we take a illegal instruction program check.

**Comment by shenki** [comment]
@aik appears to be working on a qemu fix here: https://lore.kernel.org/qemu-devel/20220504065536.3534488-1-aik@ozlabs.ru/

His patch fixes the pseries qemu machine when running with x-vof=on.

In the commit message he mentions what works and what doesn't:

> Note #1: SLOF (x-vof=off) still cannot boot a big endian zImage as
> SLOF enables MSR_SF for everything loaded by QEMU and this leads to early
> crash of 32bit zImage.

> Note #2: BE/LE vmlinux images set MSR_SF in early boot so these just work;
> a LE zImage restores MSR_SF after every CI call and we are lucky enough
> not to crash before the first CI call.

**Comment by mpe** [comment]
One thing we could try is making `PPC64_BOOT_WRAPPER` user selectable, and turn that on for BE builds. That would mean the BE zImage could be 64-bit, like the LE one.

**Comment by shenki** [comment]
| kernel | pseries,x-vof=off | pseries,x-vof=on | powernv |
| -------- | ---------- | ----------- | ----------- |
| vmlinux BE | ✓ | ✓ | ✓ | 
| vmlinux LE | ✓ | ✓ | ✓ | 
| zImage.pseries BE | x | ✓⁺ | N/A |
| zImage.pseries LE |  ✓| ✓| N/A |
| zImage.epapr BE | N/A | N/A | x |
| zImage.epapr LE | N/A | N/A | ✓ |

 ⁺ works only with Alexey's qemu patch applied, and must set kernel-addr=0

**Comment by aik** [comment]
> The zImage built for `ppc64_defconfig` is a 32-bit binary. It seems that SLOF/qemu isn't loading it properly.

btw QEMU has trace points (enable via `-trace events=/home/aik/qemu_trace_events`) and with the defaults, `loader_write_rom` gives a hint of what goes wrong:

```
loader_write_rom slof.bin: @0x0 size=0xe3350 ROM=0                                        
loader_write_rom /home/aik/pbuild/kernel-be-defconfig/arch/powerpc/boot/zImage.pseries ELF program header segment 0: @**0x4400000** size=0x9ece52 ROM=0                                  
```

**Comment by shenki** [comment]
> One thing we could try is making `PPC64_BOOT_WRAPPER` user selectable, and turn that on for BE builds. That would mean the BE zImage could be 64-bit, like the LE one.

I tried this and it made the linker segfault:

```apt policy binutils
binutils:
  Installed: 2.38-4
```
```
$ powerpc64le-linux-gnu-ld -m elf32ppc -T arch/powerpc/boot/zImage.lds -Ttext 0x20000000 -pie --no-dynamic-linker -z notext -o arch/powerpc/boot/zImage.epapr -Map wrapper.map arch/powerpc/boot/pseries-head.o arch/powerpc/boot/epapr.o arch/powerpc/boot/epapr-wrapper.o ./zImage.2535927.o arch/powerpc/boot/wrapper.a
```
```
#0  bfd_link_hash_traverse (htab=0xaaaaba069a60, func=func@entry=0xaaaab9ec8760 <lang_one_common>, info=info@entry=0x0)
    at ../../bfd/linker.c:669
669	../../bfd/linker.c: No such file or directory.
(gdb) bt
#0  bfd_link_hash_traverse (htab=0xaaaaba069a60, func=func@entry=0xaaaab9ec8760 <lang_one_common>, info=info@entry=0x0)
    at ../../bfd/linker.c:669
#1  0x0000aaaab9ed3d84 in lang_common () at ../../ld/ldlang.c:7183
#2  lang_process () at ../../ld/ldlang.c:8193
#3  0x0000aaaab9ebe290 in main (argc=<optimized out>, argv=<optimized out>) at ../../ld/ldmain.c:497
(gdb) bt full
#0  bfd_link_hash_traverse (htab=0xaaaaba069a60, func=func@entry=0xaaaab9ec8760 <lang_one_common>, info=info@entry=0x0)
    at ../../bfd/linker.c:669
        p = 0x20
        i = 100
#1  0x0000aaaab9ed3d84 in lang_common () at ../../ld/ldlang.c:7183
No locals.
#2  lang_process () at ../../ld/ldlang.c:8193
No locals.
#3  0x0000aaaab9ebe290 in main (argc=<optimized out>, argv=<optimized out>) at ../../ld/ldmain.c:497
        emulation = 0xfffff8d005ec "elf32ppc"
        start_time = 919
```

The reason I went down this path was I assumed booting the wrapper in qemu would work, but it never has. That's annoying if you're testing changes in the wrapper, but it's not really important for any real machine.

It might be just as useful to document the configurations that are expected to work, so we can point users at that.
